# why numpy?
1. numpy operations are often a lot faster than classic python!
1. numpy uses c to be very fast in a process called vectorization / broadcasting

In [12]:
import numpy as np

## Datatypes and Attributes

In [13]:
#main datatypes is an ndarray!
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [14]:
type(a1)

numpy.ndarray

In [15]:
a2 = np.array([[1, 2, 3.3],
                   [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])

a3_fixed = np.array([[[1, 2, 3],
                          [4, 5, 6]],
                         [[7, 8, 9],
                          [10, 11, 12]],
                         [[13, 14, 15],
                          [16, 17, 18]]])

In [18]:
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a3_fixed.shape)

(3,)
(2, 3)
(2, 3, 3)
(3, 2, 3)


In [20]:
a1.ndim, a2.ndim, a3.ndim #print out multiple dimensions

(1, 2, 3)

In [21]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [23]:
a1.size, a2.size, a3.size #total number of elements

(3, 6, 18)

## Create a dataframe from an array

In [26]:
import pandas as pd
df = pd.DataFrame(a2) #pandas is built upon numpy!
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays!

In [28]:
ones = np.ones(shape=(2,3)) #creates an n-dimensional array filled with 1s that we can manipulate
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
zeros = np.zeros(shape=(2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
rangearray = np.arange(2, 17, 3)
rangearray

array([ 2,  5,  8, 11, 14])

In [31]:
randomarray = np.random.randint(1,18,size=(3,4))
randomarray

array([[4, 7, 3, 6],
       [9, 2, 3, 8],
       [2, 8, 1, 5]])

In [33]:
randomarray_2 = np.random.random((5,3))
randomarray_2

array([[0.45139222, 0.47885146, 0.05533357],
       [0.17489165, 0.32475147, 0.000991  ],
       [0.77283373, 0.77077022, 0.29423752],
       [0.21494482, 0.77149779, 0.77807405],
       [0.25066152, 0.55979908, 0.76924573]])

In [34]:
randomarray_3 = np.random.rand(5,3)
randomarray_3

array([[0.58769204, 0.74309125, 0.61560681],
       [0.36928244, 0.19168062, 0.44854431],
       [0.82846022, 0.23299632, 0.95227177],
       [0.86913941, 0.14008287, 0.96327359],
       [0.63977846, 0.82492353, 0.97621805]])

In [37]:
#you can set a seed to always get the same random numbers!
np.random.seed(seed=0)
not_so_random_array = np.random.randint(10, size=(5,3))
not_so_random_array

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and matricies

In [39]:
np.unique(not_so_random_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a3[0], a3[0][1:]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[4, 5, 6],
        [7, 8, 9]]))