# We'll cover the most fundamental concepts in tensorflow

In [3]:
import tensorflow as tf
print(tf.__version__)

2.11.1


In [5]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
matrix = tf.constant([[10, 7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [14]:
#number of dimensions starts at 0? it's related to the number of elements in shape
scalar.ndim, vector.ndim, matrix.ndim

(0, 1, 2)

In [18]:
#ususally want to store floats rather than ints, and can store as float16 to save space
matrix2 = tf.constant([[10., 7.],
                       [3., 2.],
                       [8., 9.]],
                       dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [19]:
matrix2.ndim

2

In [20]:
#let's make a tensor! higher dimensions!
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                         [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [21]:
tensor.ndim

3

## What we've learned thus far:
1. Scalar: a number
1. Vector: number and a direction (e.g. wind speed and direction)
1. Matrix: 2x2 set of numbers
1. Tensor: n-dimensional array of numbers

In [23]:
#tf.variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

In [24]:
changeable_tensor[0], unchangeable_tensor[0]

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>)

In [25]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [26]:
#we need to use assignment to change variable tensors!
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [27]:
#constants aren't changeable, though
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

You usually won't need to determine constant vs Variable, but if in doubt use constant and change it later
# Creating Random Tensors!
This is especially helpful if you're trying to start at a random point, e.g. a starting set of weights that you want to begin training on!

In [33]:
random1 = tf.random.Generator.from_seed(42)
random_normal = random1.normal(shape=(3, 2))
random_normal_2 = random1.normal(shape=(3,2))
random_uniform = random1.uniform(shape=(3,2))
random_normal, random_uniform, random_normal == random_normal_2
#false because random1 is the number generator that normal/uniform run on to create new tensors

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.33853185, 0.33070397],
        [0.9244    , 0.9586116 ],
        [0.8871614 , 0.6129334 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# Shuffling the order of values in a tensor
For example, if the tests we've created are ordered in a way that will bias our model...

In [34]:
tensor = tf.constant([[10, 7],
                      [3, 4],
                      [2, 5]])

In [39]:
tf.random.shuffle(tensor) #will default to shuffling along the first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [51]:
#shuffling depends on both a global and a local seed
print(tf.random.shuffle(tensor, seed=42))
print(tf.random.shuffle(tensor, seed=42))
#https://www.tensorflow.org/api_docs/python/tf/random/set_seed

tf.Tensor(
[[ 3  4]
 [10  7]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [54]:
#to make reproducable experiments, we want to constantly randomly shuffle our tensors
tf.random.set_seed(42)
tf.random.shuffle(tensor, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [56]:
print(tf.ones([3,5]))
print(tf.zeros([2,6]))

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(2, 6), dtype=float32)


In [63]:
#you should turn numpy arrays into tensors to work on GPUs or TPUs (optimized)
import numpy as np
#vectors are often lowercase, matricies are often capitalized
#X = tf.constant([[1,2],[3,4]])
#y = tf.constand([1,2,3,4])
numpy_A = np.arange(1, 25, dtype=np.int32)
a = tf.constant(numpy_A)
A_prime = tf.constant(numpy_A, shape=(2,3,4))
a, A_prime


(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

# Getting info from tensors!