# We'll cover the most fundamental concepts in tensorflow

In [1]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [2]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [4]:
matrix = tf.constant([[10, 7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [5]:
#number of dimensions starts at 0? it's related to the number of elements in shape
scalar.ndim, vector.ndim, matrix.ndim

(0, 1, 2)

In [6]:
#ususally want to store floats rather than ints, and can store as float16 to save space
matrix2 = tf.constant([[10., 7.],
                       [3., 2.],
                       [8., 9.]],
                       dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [7]:
matrix2.ndim

2

In [8]:
#let's make a tensor! higher dimensions!
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                         [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [9]:
tensor.ndim

3

## What we've learned thus far:
1. Scalar: a number
1. Vector: number and a direction (e.g. wind speed and direction)
1. Matrix: 2x2 set of numbers
1. Tensor: n-dimensional array of numbers

In [10]:
#tf.variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

In [11]:
changeable_tensor[0], unchangeable_tensor[0]

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>)

In [12]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [13]:
#we need to use assignment to change variable tensors!
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [14]:
#constants aren't changeable, though
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

You usually won't need to determine constant vs Variable, but if in doubt use constant and change it later
# Creating Random Tensors!
This is especially helpful if you're trying to start at a random point, e.g. a starting set of weights that you want to begin training on!

In [15]:
random1 = tf.random.Generator.from_seed(42)
random_normal = random1.normal(shape=(3, 2))
random_normal_2 = random1.normal(shape=(3,2))
random_uniform = random1.uniform(shape=(3,2))
random_normal, random_uniform, random_normal == random_normal_2
#false because random1 is the number generator that normal/uniform run on to create new tensors

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.33853185, 0.33070397],
        [0.9244    , 0.9586116 ],
        [0.8871614 , 0.6129334 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# Shuffling the order of values in a tensor
For example, if the tests we've created are ordered in a way that will bias our model...

In [16]:
tensor = tf.constant([[10, 7],
                      [3, 4],
                      [2, 5]])

In [17]:
tf.random.shuffle(tensor) #will default to shuffling along the first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [18]:
#shuffling depends on both a global and a local seed
print(tf.random.shuffle(tensor, seed=42))
print(tf.random.shuffle(tensor, seed=42))
#https://www.tensorflow.org/api_docs/python/tf/random/set_seed

tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)


In [19]:
#to make reproducable experiments, we want to constantly randomly shuffle our tensors
tf.random.set_seed(42)
tf.random.shuffle(tensor, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [20]:
print(tf.ones([3,5]))
print(tf.zeros([2,6]))

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(2, 6), dtype=float32)


In [21]:
#you should turn numpy arrays into tensors to work on GPUs or TPUs (optimized)
import numpy as np
#vectors are often lowercase, matricies are often capitalized
#X = tf.constant([[1,2],[3,4]])
#y = tf.constant([1,2,3,4])
numpy_A = np.arange(1, 25, dtype=np.int32)
a = tf.constant(numpy_A)
A_prime = tf.constant(numpy_A, shape=(2,3,4))
a, A_prime

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

# Getting info from tensors!
* Shape: number of elements in each dimension of a tensor
* Rank: nmumber of tensor dimensions
* Axis or Dimension: a particular dimension of a tensor, accessed by tensor[0] or tensor[:, 1]
* Size: total number of elements in a tensor as a whole

In [22]:
#create a rank 4 tensor...
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor[0] #0th axis

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
# get various attributes from our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


In [33]:
#Indexing and expanding tensors - just like lists!
#first two elements of each dimension of our tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
#get the first element from each dimension from each index except for the last one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
#get teh second to last element for the first index from each other axis
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [40]:
# Adding dimensions
rank_2_tensor = tf.random.uniform(shape=[2, 2], minval=1, maxval=9)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6.9218464, 3.7150555],
       [5.5540047, 4.5849113]], dtype=float32)>

In [42]:
#get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.7150555, 4.5849113], dtype=float32)>

In [44]:
# add a dimension - 2 methods
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[6.9218464],
        [3.7150555]],

       [[5.5540047],
        [4.5849113]]], dtype=float32)>

In [45]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[6.9218464],
        [3.7150555]],

       [[5.5540047],
        [4.5849113]]], dtype=float32)>

In [46]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[6.9218464, 3.7150555]],

       [[5.5540047, 4.5849113]]], dtype=float32)>

In [47]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[6.9218464, 3.7150555],
        [5.5540047, 4.5849113]]], dtype=float32)>

In [48]:
# Tensor Operations!
#modify ALL values in a tensor using default operators (+, -, *, /)
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10 # note that right now this doesn't actually modify the tensor, it just returns it

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [49]:
tensor*10, tensor-10, tensor/100

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.1 , 0.07],
        [0.03, 0.04]])>)

In [50]:
#tensorflow functions also exist! tf.multiply == tf.math.multiply
#on a GPU, the tensorflow functions will be faster than the python methods
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [56]:
# Matrix multiplication!!
tensor_1 = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
tensor_2 = tf.constant([[3, 5], [6, 7], [1, 8]])
tf.tensordot(tensor_1, tensor_2, axes=1)
# axes=1 is matrix multiplication, axes=0 can give you the outer product (order 4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [57]:
#or matmul exists...
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [60]:
#python matrix multiplication is @ - but remember, on a GPU/TPU, it's slower!
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [61]:
# what could we do if we wanted to do tensor 2 @ tensor 1? reshape it!
tf.matmul( tf.reshape(tensor_2, shape=(2, 3)), tensor_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[56, 34, 38],
       [38, 40, 60]])>

In [62]:
#transpose is different that reshape...
tf.matmul( tf.transpose(tensor_2), tensor_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 21, 24],
       [78, 48, 56]])>

In [76]:
testing_transpose = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]] ])
testing_transpose.numpy(), \
  tf.transpose(testing_transpose, perm=(0, 1, 2)).numpy() \
    , tf.transpose(testing_transpose, perm=(0, 2, 1)).numpy() \
    , tf.transpose(testing_transpose, perm=(1, 0, 2)).numpy() \
    , tf.transpose(testing_transpose, perm=(1, 2, 0)).numpy() \
    , tf.transpose(testing_transpose, perm=(2, 1, 0)).numpy() \
    , tf.transpose(testing_transpose, perm=(2, 0, 1)).numpy()

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 array([[[1, 3],
         [2, 4]],
 
        [[5, 7],
         [6, 8]]]),
 array([[[1, 2],
         [5, 6]],
 
        [[3, 4],
         [7, 8]]]),
 array([[[1, 5],
         [2, 6]],
 
        [[3, 7],
         [4, 8]]]),
 array([[[1, 5],
         [3, 7]],
 
        [[2, 6],
         [4, 8]]]),
 array([[[1, 3],
         [5, 7]],
 
        [[2, 4],
         [6, 8]]]))

In [79]:
#what can tensordot do?
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[7, 8], [9, 10], [11, 12]])
tf.tensordot(X, tf.transpose(Y), axes=1), tf.tensordot(Y, tf.transpose(X), axes=1)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  53,  83],
        [ 29,  67, 105],
        [ 35,  81, 127]])>)

In [80]:
#...they're transposed themselves! X'Y == (Y'X)'
tf.tensordot(X, tf.transpose(Y), axes=1) == tf.transpose( tf.tensordot(Y, tf.transpose(X), axes=1))

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [81]:
#what's this outer product?
tf.tensordot(X, tf.transpose(Y), axes=0)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 7,  9, 11],
         [ 8, 10, 12]],

        [[14, 18, 22],
         [16, 20, 24]]],


       [[[21, 27, 33],
         [24, 30, 36]],

        [[28, 36, 44],
         [32, 40, 48]]],


       [[[35, 45, 55],
         [40, 50, 60]],

        [[42, 54, 66],
         [48, 60, 72]]]])>

In [84]:
#can we change the datatype of a tensor? most will be int32 when created
B = tf.constant([1.7, 7.4])
C = tf.constant([1, 7])
B.dtype, C.dtype


(tf.float32, tf.int32)

In [87]:
#reducing precision from float32 to float16
#modern accelerators can run float16 and bfloat16 datatypes faster
D = tf.cast(B, dtype=tf.float16)
E = tf.cast(C, dtype=tf.float32)
D.dtype, E.dtype

(tf.float16, tf.float32)

In [88]:
# Aggregating tensors!
# taking multiple values from tensors down into smaller, more understandable values

#absolute values
D = tf.constant([-7, -10])
tf.abs(D)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [90]:
#minimum, maximum, mean, sum
tf.reduce_min(D), tf.reduce_max(D), tf.reduce_mean(D), tf.reduce_sum(D)

(<tf.Tensor: shape=(), dtype=int32, numpy=-10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-17>)

In [93]:
#why is the mean 8? because it's an int32, not a float*
tf.reduce_mean(tf.cast(D, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=-8.5>

In [98]:
E = tf.constant(np.random.randint(0, 100, 50))
tf.math.reduce_std(tf.cast(E, dtype=tf.float16)), \
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

(<tf.Tensor: shape=(), dtype=float16, numpy=28.53>,
 <tf.Tensor: shape=(), dtype=float16, numpy=814.0>)

In [101]:
#find the positional maximum and minimum - basically where the max and the min are
tf.argmax(E), tf.argmin(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=int64, numpy=7>)

In [102]:
F = tf.reshape(E, shape=(5, 2, 5))
F

<tf.Tensor: shape=(5, 2, 5), dtype=int32, numpy=
array([[[22,  8, 59, 46, 19],
        [51, 47,  0, 78, 93]],

       [[ 4, 20, 26, 20, 78],
        [89, 99, 65, 50, 41]],

       [[89, 60,  7, 54, 16],
        [30, 44, 85, 97, 15]],

       [[28, 22, 27, 74, 88],
        [34, 84, 81, 32, 33]],

       [[30, 10,  4, 54, 49],
        [44, 23, 21, 61, 81]]])>

In [106]:
tf.argmax(F, axis=0), tf.argmax(F, axis=1), tf.argmax(F, axis=2)

(<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
 array([[2, 2, 0, 3, 3],
        [1, 1, 2, 2, 0]], dtype=int64)>,
 <tf.Tensor: shape=(5, 5), dtype=int64, numpy=
 array([[1, 1, 0, 1, 1],
        [1, 1, 1, 1, 0],
        [0, 0, 1, 1, 0],
        [1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1]], dtype=int64)>,
 <tf.Tensor: shape=(5, 2), dtype=int64, numpy=
 array([[2, 4],
        [4, 1],
        [0, 3],
        [4, 1],
        [3, 4]], dtype=int64)>)

In [108]:
# Squeezing tensors - removing all single dimensions
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.803156  , 0.49777734, 0.37054038, 0.9118674 , 0.637642  ,
           0.18209696, 0.63791955, 0.27701473, 0.04227114, 0.84219384,
           0.90637195, 0.222556  , 0.9198462 , 0.68789077, 0.42705178,
           0.878158  , 0.6943959 , 0.46567595, 0.52925766, 0.33019018,
           0.12754858, 0.16153514, 0.5085137 , 0.44301772, 0.35205877,
           0.8969147 , 0.24940813, 0.76328313, 0.85935795, 0.08480155,
           0.20418596, 0.28848922, 0.65142167, 0.7106751 , 0.8695041 ,
           0.23745108, 0.6688912 , 0.7115667 , 0.21899498, 0.7702793 ,
           0.45055628, 0.95493364, 0.71695936, 0.98945487, 0.1511141 ,
           0.06240606, 0.15209746, 0.99522185, 0.7830266 , 0.10455871]]]]],
      dtype=float32)>

In [109]:
G_squeeze = tf.squeeze(G)
G_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.803156  , 0.49777734, 0.37054038, 0.9118674 , 0.637642  ,
       0.18209696, 0.63791955, 0.27701473, 0.04227114, 0.84219384,
       0.90637195, 0.222556  , 0.9198462 , 0.68789077, 0.42705178,
       0.878158  , 0.6943959 , 0.46567595, 0.52925766, 0.33019018,
       0.12754858, 0.16153514, 0.5085137 , 0.44301772, 0.35205877,
       0.8969147 , 0.24940813, 0.76328313, 0.85935795, 0.08480155,
       0.20418596, 0.28848922, 0.65142167, 0.7106751 , 0.8695041 ,
       0.23745108, 0.6688912 , 0.7115667 , 0.21899498, 0.7702793 ,
       0.45055628, 0.95493364, 0.71695936, 0.98945487, 0.1511141 ,
       0.06240606, 0.15209746, 0.99522185, 0.7830266 , 0.10455871],
      dtype=float32)>

In [110]:
#one-hot encoding, a form of encoding that is essentially a identity matrix?
some_list = [0, 1, 2, 3]  #red, green, blue, and purple
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [111]:
tf.one_hot(some_list, depth=4, on_value="I love ML", off_value="off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love ML', b'off', b'off', b'off'],
       [b'off', b'I love ML', b'off', b'off'],
       [b'off', b'off', b'I love ML', b'off'],
       [b'off', b'off', b'off', b'I love ML']], dtype=object)>

In [112]:
tf.one_hot(some_list, depth=2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [117]:
#squaring, log, sqare root
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [114]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [121]:
tf.sqrt(tf.cast(H, dtype=tf.float16)) #only a few decimals

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [123]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [124]:
#Tensors and Numpy
J = tf.constant(np.array([3., 7., 10]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [126]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [128]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [130]:
#if there's something that works with numpy but not tensorflow, it's easy to move back and forth!
#note that default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7, 10]))
tensor_J = tf.constant([3., 7, 10])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [131]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [134]:
tf.config.list_physical_devices() #home computer!

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [136]:
tf.config.list_physical_devices("GPU") #see if a GPU is available... like on google.colab

[]

In [137]:
!nvidia-smi

Mon Oct 23 23:59:32 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.19                 Driver Version: 536.19       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti   WDDM  | 00000000:02:00.0  On |                  N/A |
|  0%   43C    P8              18W / 200W |    496MiB /  8192MiB |     14%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### IF you have access to a CUDA-enabled GPU, tensorflow will use it whenever it's able to!